### PR TITLE
fix(Tile): reorder component markup for a11y

### PR DESCRIPTION
**Pull request by emyarod**
Closes IBM/carbon-components-react#1114

This PR modifies `<SelectableTile>` and `<TileGroup>` component markup to address a11y failures

#### Changelog

**Changed**

- arrange `<SelectableTile>` input field before its corresponding `<label>`
- render `<TileGroup>` as `fieldset` element rather than a `div`

### CODE REVIEW

**Comment by ZachStowellIBM** [comment]
In case you're not able to run DAP due to token issues, I've attached a screenshot of the DAP a11y results for the deploy preview for the selectable tile.

screen shot 2019-01-22 at 8 50 46 am

You can see there are no more errors related to the tiles (the two errors shown in the screenshot are due to storybook).

**Comment by emyarod** [comment]
thank you @ZachStowellIBM !

**Comment by gdelory** [comment]
Switching div to fieldset in TileGroup makes impossible to have the TileGroup as flex container with row direction, which was really convenient :(

**Comment by gdelory** [comment]
And I can't find a work around to have row directed items, here what I used to have which is now broken
https://codesandbox.io/s/5347p565jn

**Comment by gdelory** [comment]
Using inline blocks does the trick, sorry for bothering :)
https://codesandbox.io/s/q98lw3yjy9

**Comment by emyarod** [comment]
it seems `fieldset` cannot be styled as a flex container only in Chrome

glad you figured out a workaround @gdelory!

**Comment by valZho** [comment]
@emyarod While we can switch from using flex-box to just inline-block elements in the short term, changing a div into a fieldset is probably not the best idea. Instead, the existing div should have been wrapped in a fieldset. Perhaps this can still be implemented?

**Comment by emyarod** [comment]
@valZho yes feel free to open a new issue about this proposal

**Pull request merged**
