### PR TITLE
feat(FileUploaderButton): add disabled prop

### PR DESCRIPTION
**Pull request by lekterable**
Closes IBM/carbon-components-react#1444

This prop disables functionality, but the button doesn't look disabled. How can I fix it? Maybe there is some kind of class I could use?

#### Changelog

**New**

* Disabled prop

### CODE REVIEW

**Comment by lekterable** [comment]
@asudoh yeah, sure. Any ideas regarding the styles tho? This could be a bit misleading to disable just the functionality.

**Comment by asudoh** [comment]
@lekterable Good question - Do you want to do something similar to: https://github.com/IBM/carbon-components/blob/v9.43.0/src/components/button/_mixins.scss#L23-L26? Thanks!

**Comment by lekterable** [comment]
@marijohannessen all the tests passed, this is an error that CircleCi is throwing:

```
Test Suites: 144 passed, 144 total
Tests:       11 skipped, 1196 passed, 1207 total
Snapshots:   84 passed, 84 total
Time:        42.081s
Ran all test suites.
$ yarn build && node ssr-tests/*.js
$ node scripts/build.js
Deleting old build folders...
Successfully compiled 420 files with Babel.
Successfully compiled 420 files with Babel.

[!] RangeError: Exceeded size threshold of 80000 bytes (gzipped)!
RangeError: Exceeded size threshold of 80000 bytes (gzipped)!
    at Object.ongenerate (/home/circleci/repo/scripts/rollup.config.js:49:21)
    at /home/circleci/repo/node_modules/rollup/dist/rollup.js:19644:40
    at Array.forEach (<anonymous>)
    at /home/circleci/repo/node_modules/rollup/dist/rollup.js:19642:41
    at <anonymous>

One of the commands failed: Error: Command failed: /home/circleci/repo/node_modules/.bin/rollup -c scripts/rollup.config.js -o umd/carbon-components-react.min.js
    at checkExecSyncError (child_process.js:602:13)
    at execSync (child_process.js:642:13)
    at exec (/home/circleci/repo/scripts/build.js:23:3)
    at Promise.all.then (/home/circleci/repo/scripts/build.js:52:5)
    at <anonymous>
```

any ideas?

**Comment by marijohannessen** [comment]
It seems to be working again now! 🎉

**Pull request merged**
