### PR TITLE
fix(sort icon): reverse direction of svg sort direction icon

### PR DESCRIPTION
**Pull request by lovemecomputer**
Closes IBM/carbon-components-react#1111

In the headers for sortable tables, the sort direction icon is opposite that of Finder etc.

I think it was tempting to use `iconCaretDown` for *descending* order, since the words match. but graphically, most programs us an upward-facing arrow for descending order. 

resolved by swapping to use `iconCaretUp`

#### Changelog

**Changed**

* sortable headers now use `iconCaretUp` instead of `iconCaretDown`

### CODE REVIEW

**Comment by alisonjoseph** [comment]
One comment, you have this labeled as "chore". I don't believe that will trigger an automatic release? Only fix and feature will.

**Comment by lovemecomputer** [comment]
@joshblack @alisonjoseph @asudoh thanks y'all! okay, ig that was my first time to make a change that touched something a snapshot would be compared against, so i messily resolved it :p 

looks like all is go for now! i was having some issues with git on my local machine so i manually edited the snapshot inside of github. lemme know if all is cool!

**Comment by alisonjoseph** [comment]
@lovemecomputer can you check if we need to switch this icon in the `carbon-components` repo? You can see the vanilla example on the website http://carbondesignsystem.com/components/data-table/code and there is also a codepen https://codepen.io/team/carbon/full/MOEagV/

**Comment by lovemecomputer** [comment]
@alisonjoseph sorting behavior in those examples doesn't work on my end, it just rotates the arrow without actually sorting the table. however, on first click, the arrow seems to point in the correct direction for ascending order. 

maybe @asudoh can comment? [here's the file defining orientation of the sort arrow in carbon-components](https://github.com/IBM/carbon-components/blob/master/src/components/data-table-v2/_data-table-v2-sort.scss).

i'm seeing some inconsistent errors in the react sort table example behavior too—going to test locally to see if it's just a problem on storybook.

i also checked the sketch file and the icon is oriented correctly there :)

**Comment by asudoh** [comment]
@lovemecomputer Vanilla code does not take care of actual sorting. Data manipulation on table tends to involve application-specific logics, as well as JavaScript framework-specific logics, and thus we relegate that, including sorting, to user-land.

**Pull request merged**
