### PR TITLE
feat(ModalWrapper): return focus to modal trigger button on modal close

### PR DESCRIPTION
**Pull request by emyarod**
Closes IBM/carbon-components-react#1298

This PR will return focus to the element that launches the modal when the modal is closed, which should improve keyboard a11y. This is accomplished by attaching a ref to the trigger button, which is then used to focus on the button in the callback of the `setState` operation when closing the modal

#### Changelog

**New**

* attach a ref to the `<Button>` in `<ModalWrapper>` which will launch the `<Modal>` element
* add logic to call `HTMLElement.focus()` on the button after modal is closed

**Changed**

* access `<Modal>` refs through the refs' `current` property

### CODE REVIEW

**Comment by emyarod** [comment]
hi @asudoh do you mean accessing the ref through the `current` attribute? If I'm not mistaken, I don't think I can use it in this case because `<Button>` is a stateless functional component. Am I incorrectly understanding `ref` usage with functional components?

**Comment by joshblack** [comment]
@emyarod I think what @asudoh is referring to is that if you use the form `React.createRef` for a component instance property, like `this.triggerButton`, then you would do `inputRef={this.triggerButton}` instead of the old callback style where you assign the button to `this.triggerButton`.

Ref: https://reactjs.org/docs/refs-and-the-dom.html#creating-refs

**Comment by emyarod** [comment]
gotcha @joshblack, I think that is what allows me to use the `current` attribute like I mentioned earlier. Is [this](https://github.com/IBM/carbon-components-react/pull/1299/commits/f9e8fe35d2691ae2c1acc940d583afbffbbe0a69) more in line with what we want?

**Comment by emyarod** [comment]
@joshblack is [this test](https://github.com/IBM/carbon-components-react/pull/1299/commits/cf1851de40ee98e3d21ba4a7da1cfa303d8b813d) sufficient for testing this new behavior?

**Pull request merged**
