### PR TITLE
fix(DatePickerInput): apply nolabel class if label is undefined

### PR DESCRIPTION
**Pull request by lekterable**
Closes IBM/carbon-components-react#1289

If label is undefined `bx--date-picker--nolabel` class will be applied to container, thanks to that icon will be displayed correctly.

#### Changelog

**New**

* `bx--date-picker--nolabel` class

### CODE REVIEW

**Comment by lekterable** [comment]
wow ur fast @asudoh

**Comment by lekterable** [comment]
@tw15egan that's a good catch, thanks! I just checked and this:
>  Seems like adding bx--date-picker--nolabel to the bx--date-picker container fixes the issue.
doesn't work for both, using this alone single calendar icon is rendered too high.
Looks like we have to have this in both components.

**Comment by tw15egan** [comment]
Sounds good. Once the changes are pushed up I'll take a look

**Comment by lekterable** [comment]
Now it should work for both of them, WDYT @tw15egan ?

**Pull request merged**
