### PR TITLE
feat(TextInput): allow TextInput to handle refs like a native input e…

### PR DESCRIPTION
**Pull request by silesky**
Closes IBM/carbon-components-react#1191

added ability to forward refs

### CODE REVIEW

**Comment by silesky** [comment]
Hey @asudoh, I would be happy to contribute more, but that's a significant
amount of code changes (mostly, the tests).

Since this issue is really about a single input (arguably, the most
important), I would rather see this merged in and take out enother issur/PR
for the rest of the form elements.

Thoughts?

**Comment by asudoh** [comment]
@silesky I saw your immediate need for the issue to be fixed, OTOH I saw myself reluctant to introduce this only to `<TextInput>` for the sake of immediate need, because confusions arose from feature, etc. inconsistency among similar components has gradually become bigger in recent months. That said, it'd be great if you can address `<Checkbox>` and `<Select>` as the start. Thanks!

**Comment by silesky** [comment]
@asudoh Select and Checkbox added

**Comment by emyarod** [comment]
we can create a separate issue for the remaining components not covered in this PR

**Pull request merged**
