### PR TITLE
docs(FileUploader): restore 'none' `buttonKind` knob

### PR DESCRIPTION
**Pull request by emyarod**
Restore 'none' `buttonKind` knob which was mistakenly replaced by defaulting to `buttonKind="primary"` in #1200 

Related: #1199

### CODE REVIEW

**Comment by emyarod** [comment]
wait @joshblack @alisonjoseph I marked it WIP to delay merging since I want to make sure I'm on the same page as @asudoh [here](https://github.com/IBM/carbon-components-react/pull/1200#discussion_r210598781)

**Comment by emyarod** [comment]
wait @joshblack @alisonjoseph I marked this PR as [WIP] to delay merging and [make sure I was in line](https://github.com/IBM/carbon-components-react/pull/1200#discussion_r210598781) with @asudoh's initial changes

**Comment by alisonjoseph** [comment]
Oops!! Sorry about that 😞

@joshblack @asudoh let me know if I need to revery anything here?

**Comment by alisonjoseph** [comment]
docs doesn't trigger a deploy so we can just open a new PR if we need to update again.

**Comment by asudoh** [comment]
The change looks good to me - Thanks @emyarod for the fix and trying to check with me!

**Pull request merged**
