### PR TITLE
fix(clickable-tile): add rel prop

### PR DESCRIPTION
**Pull request by alisonjoseph**
Adds the ability to add a rel value to the clickable tile 

_related to building out Gatsby site, google lighthouse recommends `rel="noopener` on links opening in a new window_

### CODE REVIEW

**Comment by asudoh** [comment]
Would we want to keep just the prop type? In this way consumers know that it’s supported, the type is checked, but don’t need any additional (our) code to copy the prop value to the inner-node. What do you think?

**Comment by alisonjoseph** [comment]
@asudoh updated to just have prop type

**Comment by alisonjoseph** [comment]
done @joshblack 😸

**Comment by joshblack** [comment]
You rock! 🙏

**Comment by alisonjoseph** [comment]
thanks for keeping us accountable 😉 @joshblack

**Pull request merged**
