### PR TITLE
fix: Adds an aria-label to the div surrounding the tooltip icon, reso…

### PR DESCRIPTION
**Pull request by zgrossbart**
…lves #1697.

Closes IBM/carbon-components-react #1697 

This is a small change to add the `aria-label` attribute in the parent div element when it is an interactive element.

### CODE REVIEW

**Comment by joshblack** [comment]
@zgrossbart should the content of the icon populate the contents for the node? For example, if I had the following markup:

```html
<button type="button">
  <svg width="24" height="24" viewBox="0 0 25 24" role="img" aria-label="Hi there">
    <circle cx="12" cy="12" r="12"></circle>
  </svg>
</button>
```

In Chrome, it would be read as `Hi there`:

image

Just wanted to check to see if this is really the issue, where we are relying on internals to be read, when in reality we need `aria-label` on the parent.

**Comment by zgrossbart** [comment]
The screen readers need the `aria-label` on the parent because that is the interactive element.

**Comment by joshblack** [comment]
@zgrossbart what I'm asking about is when we need to include `aria-label`/`aria-labelledby`, versus when it is read from content.

If we took the button example from above and made it: `<button>Submit</button>` would you agree this would not need an `aria-label` or `aria-labelledby` attribute? e.g. `<button aria-label="Submit">Submit</button>`

**Comment by zgrossbart** [comment]
We do need the icon to have some kind of either `aria-label` or `aria-labelledby`.  However, if we use `aria-labelledby` then we need an id for the button element.  I don't think we really need this for screen readers, but we do need this for the DAP tools.

**Comment by joshblack** [comment]
Yeah, was thinking that was the case and it might be missing `role="img"` or something similar which is causing the issue. 

I think this is a great interim fix though while we figure it out, thanks!

**Comment by zgrossbart** [comment]
Thanks @joshblack.  Are we waiting on something else before merging this?

**Pull request merged**
