### PR TITLE
fix: apply correct aria label prop for radio

### PR DESCRIPTION
**Pull request by nelsonchen90**
apply correct aria label prop for radio select on data table. resolving the dev warning about `Invalid ARIA attribute`

#### Changelog

**Changed**
- apply correct aria label prop for radio select on data table.

### CODE REVIEW

**Comment by nelsonchen90** [comment]
error on dev env:
image

**Comment by asudoh** [comment]
Also @nelsonchen90 do you want to take care of the snapshot? Thanks!

**Comment by nelsonchen90** [comment]
@asudoh @emyarod thanks for the review,
yes I will take care of the snapshots!

**Comment by nelsonchen90** [comment]
need more work, what's happening now is:
image

the 'Select row' is not expected

**Comment by nelsonchen90** [comment]
@emyarod @asudoh 
I need your input here:
in RadioButton, we are mixing the `aria-label` with the text on the `<label>`:
https://github.com/IBM/carbon-components-react/blob/master/src/components/RadioButton/RadioButton.js#L125-L131

should I keep it as is? see the screenshot in the comment above

**Comment by emyarod** [comment]
@nelsonchen90 I guess we can either pass in the value of `ariaLabel` as hyphen-case `aria-label` to RadioButton, or we can also add `hideLabel` as you suggested. Adding `hideLabel` would be consistent with other components like checkbox currently, and eventually we can refactor our components to avoid camelCase `ariaLabel` altogether and just use hyphen-case `aria-label` directly (related https://github.com/IBM/carbon-components-react/issues/1662). So for now I am leaning towards adding `hideLabel`, but would be interested in hearing others' thoughts on this

**Comment by asudoh** [comment]
👍 for `hideLabel` - @nelsonchen90 Seems that snapshot update is still needed, could you take care of this? Thanks!

**Comment by nelsonchen90** [comment]
@asudoh
sorry for late response!
yes I will add the hideLabel and then refresh the snapshot

**Comment by nelsonchen90** [comment]
@asudoh @emyarod 
I updated the PR with the `hideLabel` and fixes the test snapshot

**Comment by emyarod** [comment]
@nelsonchen90 it looks like there is a merge conflict, would you mind updating your snapshots?

**Comment by nelsonchen90** [comment]
@emyarod done.

**Comment by emyarod** [comment]
thanks @nelsonchen90 !

**Pull request merged**
