### PR TITLE
feat(Slider): Add handle release callback prop

### PR DESCRIPTION
**Pull request by tombrowndev**
Adds a onRelease callback prop for the Slider. It fires when the user lets go of the slider handle and returns the value similar to the onChange.

### CODE REVIEW

**Comment by tombrowndev** [comment]
Please see associated issue for this feature request:

https://github.com/IBM/carbon-components-react/issues/1568

**Comment by asudoh** [comment]
Oh BTW great to have tests @tombrowndev!

**Comment by tombrowndev** [comment]
Thanks, I shall add some unit tests for this too

@asudoh

**Comment by joshblack** [comment]
Hi @tombrowndev! Going to close this for now as the PR seems stale, but please feel free to comment on this and we can re-open it and get those changes in. Thanks again for the work here, we really appreciate it! 🙏

**Comment by tombrowndev** [comment]
I have updated this and created unit tests for it. Do I need to make a new PR or can this one be reopened?

**Comment by tombrowndev** [comment]
@joshblack See above

**Pull request merged**
