### PR TITLE
Update 'InnerClickListener' 

### PR DESCRIPTION
**Pull request by Calvin-Cheung**
Update InnerClickListener as the current implementation does not work if elements disappear from the DOM; if an element is clicked and it goes away such as a toggle open/close icon switching states, it should not trigger an onClickOutside event

#### Changelog

**New**

- added test case for InnerClickListener-test

**Changed**

- check if event target exists in DOM

### CODE REVIEW

**Comment by Calvin-Cheung** [comment]
Hi @asudoh, I have reverted back to my previous fix since searching up from the target seems more verbose and complicated than just searching within document.body. Please take a look?

**Comment by asudoh** [comment]
@Calvin-Cheung thank you for asking - Come up with a counter-suggestion, hope it makes sense to you.

**Comment by Calvin-Cheung** [comment]
@asudoh does that mean you'll think of a counter-suggestion? Just confirming - thank you! Hope the test helps

**Comment by Calvin-Cheung** [comment]
Thank you @asudoh!

**Pull request merged**
