### PR TITLE
fix(Slider): prop -> state sync for values

### PR DESCRIPTION
**Pull request by asudoh**
Given this is a breaking change, the fix is roped off under componentsX feature flag.

Refs #1369.

#### Changelog

**Changed**

* A new prop -> state sync code reacting to change in `value`, `min` and `max` props.

### CODE REVIEW

**Comment by alisonjoseph** [comment]
Adding feature flags for breaking changes like this makes me a little nervous. It feels like it could easily get really complicated/messy. Thoughts @IBM/carbon-developers ?

**Comment by joshblack** [comment]
@asudoh seems like we're changing this component from an un-controlled to controlled component with this change? I might be reading things wrong, so let me know if not 👍

**Comment by asudoh** [comment]
@alisonjoseph Great point, let me share what we just discussed - The added code complexity is very valid concern. The plan to mitigate that is removing the old code a couple of weeks after new code being stable (new release), at latest. OTOH feature flag is a great way to replace the jet engine while still flying - Allowing us to make breaking changes without having to branch off the codebase.

@joshblack Good question, [slider has been a controlled component](https://github.com/IBM/carbon-components-react/blob/v6.38.0/src/components/Slider/Slider.js#L133-L135), and this PR doesn't change that.

**Comment by joshblack** [comment]
Anything else you need to merge this in @asudoh? I say go for it if not! 🚀

**Pull request merged**
