### PR TITLE
fix(a11y): avoid empty label in ToggleSmall

### LINKED ISSUE #1183: A11Y: ToggleSmall: Provide descriptive text and proper order in toggle label elements
## Detailed description

> Describe in detail the issue you're having.

Label 'for' for ToggleSmall needs to have a descriptive text. The label should also be before the input component

===== ENVIRONMENT =====
IBM CI 162 Checkpoint Violation: IBM 4.1.2 Name, Role, Value
IBM Guidance: https://www.ibm.com/able/guidelines/ci162/name_role_value.html
Test Tool Type: DAP

===== DEFECT DESCRIPTION =====
The label element is used to explicitly associate a form control with a label. A label is attached to a specific form control through the use of the "for" attribute. Screen readers use the text in the label as a description of the attached form control.

===== EXPECTED RESULT =====
For more detail:
https://aat.w3ibm.mybluemix.net/token/334ed6c7-0a0d-480b-a007-47d1242d0ef8/1c0df9a2-5788-4caa-8052-67d0bcadfdac/archives/2018FebDeploy//doc/w3/help/en-US/idhi_accessibility_check_g1055.html

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug

> Is this issue related to a specific component?

ToggleSmall, and to some extend Toggle

> What did you expect to happen? What happened instead? What would you like to see changed?

The label should be rendered before the input component, and it should have a descriptive text.

```
"carbon-components-react": {
"version": "6.18.4",
...
}
```
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Cloud Internet Services

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #1183.

#### Changelog

**New**

- Invisible `<span>` in `<ToggleSmall>`'s `<label>` for assistive technologies.

### CODE REVIEW

**Comment by lovemecomputer** [comment]
was going to say the same thing. not sure if valuable to merge in this fix in now as one PR, then refactor the label>input order later?

**Comment by asudoh** [comment]
Good catch @emyarod! Some research suggested that the order is for screen magnifier: https://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-cues.html, and as @lovemecomputer pointed out, it doesn't seem to affect our small toggle. CC @dakahn

**Comment by asudoh** [comment]
Great news - Thanks alot @dakahn for testing!

**Comment by gdelory** [comment]
Hi, not sure if that's expected, but for me it's not invisible at all :) 

image

**Comment by emyarod** [comment]
@gdelory would you be able to provide a [Code Sandbox](https://codesandbox.io/s/github/IBM/carbon-components-react/tree/master/examples/codesandbox) showcasing the issue you are facing?

**Comment by gdelory** [comment]
@emyarod Please ignore this, I just double checked and I was including manually an older version of carbon-components.css (9.1 something). All my apologies for this. All looks perfect now.

**Pull request merged**
