### PR TITLE
fix(NumberInput): add no-label class if no labels provided

### PR DESCRIPTION
**Pull request by lekterable**
Closes IBM/carbon-components-react#1602

It seems like a good idea to automatically add a no-label class when there are no labels passed as a props.

#### Changelog

**Changed**

- no-label class is added automatically when there are no labels specified.

### CODE REVIEW

**Comment by lekterable** [comment]
sorry for the force push here ^ but I've mixed branches

**Comment by asudoh** [comment]
Hi @lekterable thank you very much for jumping in and my apologies for being late on review. It appears that `bx--number--helpertext` not being present when `helperText` is falsy seems to be causing the issue. Wondering if you can try adding that class always?

**Comment by lekterable** [comment]
@asudoh if it's better this way, sure!

**Comment by lekterable** [comment]
Hey, @asudoh and @joshblack I believe this one is ready for review since my last comment. Maybe you've missed my commit?

**Pull request merged**
