### PR TITLE
chore(dependencies): upgrade @carbon/icons-react

### PR DESCRIPTION
**Pull request by asudoh**
#### Changelog

**Changed**

- `@carbon/icons-react` dependency from alpha 26 to alpha 32.

### CODE REVIEW

**Comment by devnieL** [comment]
@asudoh I think that `yarn.lock` and `.yarn-offline-mirror` changes after the proper `yarn add @carbon/icons-react@0.0.1-alpha.32` should also be committed to solve the CI problem.

**Comment by joshblack** [comment]
Updated offline folder 👍 also moved to `es` directory. We should be safe including it because `es` is transpiled outside of ESM. Down to move back to `lib` though if we feel that's safer 👍

**Comment by joshblack** [comment]
Ah just kidding, will move back to `lib` since Jest will complain about `es`.

**Comment by asudoh** [comment]
Thanks @joshblack for the updates!!

**Comment by asudoh** [comment]
Withdrawing as it appears that a similar change has got into `master` - Don't hesitate to speak up if anybody thinks otherwise - Thanks!

**Comment by emyarod** [comment]
sorry @asudoh I forgot about this open PR, part of it ended up overlapping with #1838 🙇 I needed the updated dependency to fix our experimental tooltips (#1883) since the tooltip icons were not forwarding refs (https://github.com/IBM/carbon-elements/pull/231)

**Comment by asudoh** [comment]
No worries @emyarod!! Though I know people tend to be frustrated by this kind of things, I 💯 understand this kind of thing may happen and it sometimes is a good thing. We can communicate, but don't be hesitant to do the right thing as you did for tooltip!

**Pull request closed without merging**
