### PR TITLE
Add explicit display names to components

### PR DESCRIPTION
**Pull request by vpicone**
Closes IBM/carbon-components-react#1542

Storybook v4 automatically uglifies js so function names can no longer be reliably used to infer display names. The maintainers recommend adding display names explicitly.

#### Changelog

**New**

* Add explicit displayNames when they haven't already been set
* Add test to ensure that displayNames are set on new components.

### CODE REVIEW

**Comment by vpicone** [comment]
The snapshot tests fail since when they were generated, the function name was set as the 'displayName' so some of the components like `SideNavMenuItem` which are assigned to `React.forwardRef(...)` got a computed displayName of `ForwardRef`. I beliiiieve Any sort of automatic inference based on function name is gonna have this same issue.

I added a __tests__ in the component directory. Since this is more like a component requirement check and not so much a behavior check, if you guys have a better spot for the test I'm down to move it.

**Comment by vpicone** [comment]
@asudoh, yes this explicitly adds the displayName whenever it wasn't already set (usually in the dataTable subcomponents with the wrapComponent() method. 

I'll update the snapshots, I think the more descriptive names are an improvement. To me, the snapshots breaking in this way introduced me to the shortcoming of computed displayNames. For this sort of thing, using named (instead of anonymous functions) kind of fudges around manually setting the display name, but the snapshots would still need to be updated.

```javscript
// appears as <ForwardRef> (bad)
export default React.forwardRef((props, ref) => {
  return <HeaderMenu {...props} focusRef={ref} />;
});
```

vs

```javscript
// appears as <ForwardRef(headerMenu)> (still not great)
export default React.forwardRef(
function headerMenu(props, ref) => {
  return <HeaderMenu {...props} focusRef={ref} />;
});
```

**Comment by joshblack** [comment]
I'm unsure about making this change for the sake of supporting the "story source" in the addon panel. We already provide the story source directly in the default tab, and making changes only for what is already a controversial source of documentation feels off. Could we instead:

- Use the babel plugin?
  - Drawback here is that it does not work for all cases
- Update the uglify settings on webpack to not mangle names?

**Comment by vpicone** [comment]
I think both of those options are good. We could swap out the UglifyJS plugin for the one CRA uses: https://github.com/webpack-contrib/terser-webpack-plugin

After playing with the forwardRef stuff in the UI shell components, it can get a bit tricky with HOCs/exporting wrapped components. So a simpler approach could definitely be better here.

**Comment by vpicone** [comment]
@joshblack right on, I'm gonna open a new PR. I think switching to full control was prob necessary with how extensive the setup is. I think the only change I have is the useExternalCss boolean at the end needs to be true maybe.

**Pull request closed without merging**
