### PR TITLE
feat(FilterableMultiSelect): allow form validation

### PR DESCRIPTION
**Pull request by lekterable**
Closes IBM/carbon-components-react#1562

I've added two props that will let users handle validation the same way as in MultiSelect component.

#### Changelog

**New**

- invalid prop
- invalidText prop

### CODE REVIEW

**Comment by lekterable** [comment]
CircleCI:
```
yarn run v1.9.4
$ yarn prettier:diff && yarn lint && yarn test --runInBand && yarn test-ssr
$ prettier --list-different "**/*.{scss,css,js,md}"
src/components/MultiSelect/FilterableMultiSelect.js
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```
🤔

**Comment by asudoh** [comment]
Wrt CircleCI error - Do you want to re-run `yarn prettier` and see if Prettier re-formats one or more of files that were changed by you? Thanks!

**Comment by lekterable** [comment]
@asudoh 
I did. The only file I've changed is `FilterableMultiSelect.js` and it doesn't seem to be reformated after running `yarn prettier`. Any ideas?
Reformated list

**Comment by asudoh** [comment]
Hi @lekterable did you run `yarn install` beforehand...? Thanks!

**Comment by lekterable** [comment]
@asudoh okay now it went fine, really weird because after `yarn install` prettier worked different than before, maybe it was confused with my own config, thanks anyway! Also let me know if you want me to commit yarn.lock and those deleted offline packages, if not i will be happy to redo that commit.

**Comment by asudoh** [comment]
The Yarn change looks good - Thanks @lekterable for the udate!

**Pull request merged**
